name: explore_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.15
  google_fonts: ^6.2.1
  flutter_bloc: ^8.1.6
  injectable: ^2.5.0
  get_it: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  injectable_generator: ^2.6.2
  build_runner: ^2.4.13

flutter:
  assets:
    - assets/
    - assets/custom_icons/
    - assets/images/

  uses-material-design: true



